/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merchorderstudio;
import merchorderstudio.dao.ProdukDAO;
import merchorderstudio.dao.KeranjangDAO;
import merchorderstudio.model.produk;
 
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import utility.sessions;

/**
 *
 * @author Mahesa
 */
public class dashboard_home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard_home.class.getName());
    
    // ==== TAMBAHAN MULAI ====
   private final ProdukDAO produkDAO = new ProdukDAO();
    private String kategoriAktif = "Semua";
    private CardLayout cardLayout;
    private final KeranjangDAO keranjangDAO = new KeranjangDAO();
    // ==== TAMBAHAN SELESAI ====


    /**
     * Creates new form dashboard_home
     */
    public dashboard_home() {
        initComponents();
        setLocationRelativeTo(null);
        // ==== TAMBAHAN MULAI ====
        cardLayout = (CardLayout) pnlContent.getLayout();
        tampilkanProduk("Semua", 0);
        loadBannerImage();
        pasangIconKategoriDanNav();
        // ==== TAMBAHAN SELESAI ====
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlTopBar = new javax.swing.JPanel();
        btnHamburger = new javax.swing.JButton();
        lblAppTitle = new javax.swing.JLabel();
        pnlTopRight = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnCart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlBeranda = new javax.swing.JPanel();
        scrBeranda = new javax.swing.JScrollPane();
        pnlBerandaContent = new javax.swing.JPanel();
        pnlBanner = new javax.swing.JPanel();
        pnlBannerText = new javax.swing.JPanel();
        lblBannerLine1 = new javax.swing.JLabel();
        lblBannerLine2 = new javax.swing.JLabel();
        lblBannerLine3 = new javax.swing.JLabel();
        btnPesanSekarang = new javax.swing.JButton();
        lblBannerImage = new javax.swing.JLabel();
        pnlKategoriSection = new javax.swing.JPanel();
        pnlKategoriHeader = new javax.swing.JPanel();
        lblKategoriTitle = new javax.swing.JLabel();
        btnLihatSemuaKategori = new javax.swing.JButton();
        pnlKategoriList = new javax.swing.JPanel();
        btnKatSemua = new javax.swing.JButton();
        btnKatKaos = new javax.swing.JButton();
        btnKatHoodie = new javax.swing.JButton();
        btnKatMug = new javax.swing.JButton();
        btnKatSticker = new javax.swing.JButton();
        btnKatTotebag = new javax.swing.JButton();
        pnlProdukHeader = new javax.swing.JPanel();
        lblProdukTitle = new javax.swing.JLabel();
        btnLihatSemuaProduk = new javax.swing.JButton();
        pnlProdukSection = new javax.swing.JPanel();
        pnlProdukGrid = new javax.swing.JPanel();
        pnlBottomNav = new javax.swing.JPanel();
        btnNavBeranda = new javax.swing.JButton();
        btnNavPesanan = new javax.swing.JButton();
        btnNavKeranjang = new javax.swing.JButton();
        btnNavAkun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MerchOrderStudio");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(580, 580));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlTopBar.setBackground(new java.awt.Color(255, 255, 255));

        btnHamburger.setText("☰");
        btnHamburger.setBorderPainted(false);
        btnHamburger.setContentAreaFilled(false);
        btnHamburger.addActionListener(this::btnHamburgerActionPerformed);

        lblAppTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAppTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppTitle.setText("MerchOrder");

        pnlTopRight.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch.setPreferredSize(new java.awt.Dimension(140, 22));
        txtSearch.addActionListener(this::txtSearchActionPerformed);
        pnlTopRight.add(txtSearch);

        btnSearch.setText(" 🔍");
        btnSearch.setPreferredSize(new java.awt.Dimension(46, 23));
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        pnlTopRight.add(btnSearch);

        btnCart.setText("🛒");
        btnCart.addActionListener(this::btnCartActionPerformed);
        pnlTopRight.add(btnCart);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 104, 0));
        jLabel1.setText(" Studio");

        javax.swing.GroupLayout pnlTopBarLayout = new javax.swing.GroupLayout(pnlTopBar);
        pnlTopBar.setLayout(pnlTopBarLayout);
        pnlTopBarLayout.setHorizontalGroup(
            pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHamburger, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(lblAppTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pnlTopRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnlTopBarLayout.setVerticalGroup(
            pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopBarLayout.createSequentialGroup()
                .addGroup(pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTopRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAppTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(btnHamburger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.CardLayout());

        pnlBeranda.setBackground(new java.awt.Color(255, 255, 255));
        pnlBeranda.setLayout(new java.awt.BorderLayout());

        scrBeranda.setBorder(null);
        scrBeranda.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrBeranda.setPreferredSize(new java.awt.Dimension(3938, 300));

        pnlBerandaContent.setLayout(new javax.swing.BoxLayout(pnlBerandaContent, javax.swing.BoxLayout.Y_AXIS));

        pnlBanner.setBackground(new java.awt.Color(255, 255, 255));

        pnlBannerText.setBackground(new java.awt.Color(232, 232, 232));
        pnlBannerText.setPreferredSize(new java.awt.Dimension(300, 125));

        lblBannerLine1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblBannerLine1.setText("Buat Desainmu");

        lblBannerLine2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblBannerLine2.setText("Jadi Merchandise Keren");

        lblBannerLine3.setText("Cetak sesuai keinginanmu!");

        btnPesanSekarang.setBackground(new java.awt.Color(255, 140, 0));
        btnPesanSekarang.setForeground(new java.awt.Color(255, 255, 255));
        btnPesanSekarang.setText("Pesan Sekarang");
        btnPesanSekarang.addActionListener(this::btnPesanSekarangActionPerformed);

        javax.swing.GroupLayout pnlBannerTextLayout = new javax.swing.GroupLayout(pnlBannerText);
        pnlBannerText.setLayout(pnlBannerTextLayout);
        pnlBannerTextLayout.setHorizontalGroup(
            pnlBannerTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerTextLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlBannerTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBannerLine1)
                    .addComponent(lblBannerLine2)
                    .addComponent(btnPesanSekarang)
                    .addComponent(lblBannerLine3))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        pnlBannerTextLayout.setVerticalGroup(
            pnlBannerTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBannerLine1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBannerLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBannerLine3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesanSekarang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblBannerImage.setText("Gambar Baju");

        javax.swing.GroupLayout pnlBannerLayout = new javax.swing.GroupLayout(pnlBanner);
        pnlBanner.setLayout(pnlBannerLayout);
        pnlBannerLayout.setHorizontalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerLayout.createSequentialGroup()
                .addContainerGap(3410, Short.MAX_VALUE)
                .addComponent(pnlBannerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(lblBannerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        pnlBannerLayout.setVerticalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBannerLayout.createSequentialGroup()
                .addComponent(pnlBannerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBannerImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBerandaContent.add(pnlBanner);

        pnlKategoriSection.setBackground(new java.awt.Color(255, 255, 255));

        pnlKategoriHeader.setBackground(new java.awt.Color(255, 255, 255));

        lblKategoriTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKategoriTitle.setText("Kategori");

        btnLihatSemuaKategori.setForeground(new java.awt.Color(255, 140, 0));
        btnLihatSemuaKategori.setText("Lihat Semua");
        btnLihatSemuaKategori.setBorderPainted(false);
        btnLihatSemuaKategori.setContentAreaFilled(false);
        btnLihatSemuaKategori.addActionListener(this::btnLihatSemuaKategoriActionPerformed);

        javax.swing.GroupLayout pnlKategoriHeaderLayout = new javax.swing.GroupLayout(pnlKategoriHeader);
        pnlKategoriHeader.setLayout(pnlKategoriHeaderLayout);
        pnlKategoriHeaderLayout.setHorizontalGroup(
            pnlKategoriHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblKategoriTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(btnLihatSemuaKategori)
                .addGap(39, 39, 39))
        );
        pnlKategoriHeaderLayout.setVerticalGroup(
            pnlKategoriHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKategoriHeaderLayout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(pnlKategoriHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLihatSemuaKategori)
                    .addComponent(lblKategoriTitle)))
        );

        pnlKategoriList.setBackground(new java.awt.Color(255, 255, 255));
        pnlKategoriList.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnKatSemua.setText("Semua");
        btnKatSemua.setPreferredSize(new java.awt.Dimension(72, 54));
        btnKatSemua.addActionListener(this::btnKatSemuaActionPerformed);
        pnlKategoriList.add(btnKatSemua);

        btnKatKaos.setText("Kaos");
        btnKatKaos.setPreferredSize(new java.awt.Dimension(72, 54));
        btnKatKaos.addActionListener(this::btnKatKaosActionPerformed);
        pnlKategoriList.add(btnKatKaos);

        btnKatHoodie.setText("Hoodie");
        btnKatHoodie.setPreferredSize(new java.awt.Dimension(72, 54));
        btnKatHoodie.addActionListener(this::btnKatHoodieActionPerformed);
        pnlKategoriList.add(btnKatHoodie);

        btnKatMug.setText("Mug");
        btnKatMug.setPreferredSize(new java.awt.Dimension(72, 54));
        btnKatMug.addActionListener(this::btnKatMugActionPerformed);
        pnlKategoriList.add(btnKatMug);

        btnKatSticker.setText("Stiker");
        btnKatSticker.setPreferredSize(new java.awt.Dimension(72, 54));
        btnKatSticker.addActionListener(this::btnKatStickerActionPerformed);
        pnlKategoriList.add(btnKatSticker);

        btnKatTotebag.setText("Totebag");
        btnKatTotebag.setPreferredSize(new java.awt.Dimension(74, 54));
        btnKatTotebag.addActionListener(this::btnKatTotebagActionPerformed);
        pnlKategoriList.add(btnKatTotebag);

        pnlProdukHeader.setBackground(new java.awt.Color(255, 255, 255));

        lblProdukTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProdukTitle.setText("Produk Terpopuler");

        btnLihatSemuaProduk.setForeground(new java.awt.Color(255, 140, 0));
        btnLihatSemuaProduk.setText("Lihat Semua");
        btnLihatSemuaProduk.setBorderPainted(false);
        btnLihatSemuaProduk.setContentAreaFilled(false);
        btnLihatSemuaProduk.addActionListener(this::btnLihatSemuaProdukActionPerformed);

        pnlProdukSection.setBackground(new java.awt.Color(255, 255, 255));

        pnlProdukGrid.setLayout(new java.awt.GridLayout(0, 2));

        javax.swing.GroupLayout pnlProdukSectionLayout = new javax.swing.GroupLayout(pnlProdukSection);
        pnlProdukSection.setLayout(pnlProdukSectionLayout);
        pnlProdukSectionLayout.setHorizontalGroup(
            pnlProdukSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdukSectionLayout.createSequentialGroup()
                .addComponent(pnlProdukGrid, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlProdukSectionLayout.setVerticalGroup(
            pnlProdukSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdukSectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlProdukGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );

        javax.swing.GroupLayout pnlProdukHeaderLayout = new javax.swing.GroupLayout(pnlProdukHeader);
        pnlProdukHeader.setLayout(pnlProdukHeaderLayout);
        pnlProdukHeaderLayout.setHorizontalGroup(
            pnlProdukHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdukHeaderLayout.createSequentialGroup()
                .addComponent(lblProdukTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLihatSemuaProduk)
                .addGap(36, 36, 36))
            .addGroup(pnlProdukHeaderLayout.createSequentialGroup()
                .addComponent(pnlProdukSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProdukHeaderLayout.setVerticalGroup(
            pnlProdukHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdukHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProdukHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdukTitle)
                    .addComponent(btnLihatSemuaProduk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProdukSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlKategoriSectionLayout = new javax.swing.GroupLayout(pnlKategoriSection);
        pnlKategoriSection.setLayout(pnlKategoriSectionLayout);
        pnlKategoriSectionLayout.setHorizontalGroup(
            pnlKategoriSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKategoriSectionLayout.createSequentialGroup()
                .addContainerGap(3395, Short.MAX_VALUE)
                .addGroup(pnlKategoriSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlKategoriHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlKategoriSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlKategoriSectionLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(pnlProdukHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(pnlKategoriList, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlKategoriSectionLayout.setVerticalGroup(
            pnlKategoriSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlKategoriHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(pnlKategoriList, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProdukHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlBerandaContent.add(pnlKategoriSection);

        scrBeranda.setViewportView(pnlBerandaContent);

        pnlBeranda.add(scrBeranda, java.awt.BorderLayout.LINE_END);

        pnlContent.add(pnlBeranda, "Beranda");

        pnlBottomNav.setBackground(new java.awt.Color(255, 255, 255));
        pnlBottomNav.setPreferredSize(new java.awt.Dimension(300, 23));
        pnlBottomNav.setLayout(new java.awt.GridLayout(1, 4));

        btnNavBeranda.setText("Beranda");
        btnNavBeranda.setBorderPainted(false);
        btnNavBeranda.setContentAreaFilled(false);
        btnNavBeranda.addActionListener(this::btnNavBerandaActionPerformed);
        pnlBottomNav.add(btnNavBeranda);

        btnNavPesanan.setText("Pesanan");
        btnNavPesanan.setBorderPainted(false);
        btnNavPesanan.setContentAreaFilled(false);
        btnNavPesanan.addActionListener(this::btnNavPesananActionPerformed);
        pnlBottomNav.add(btnNavPesanan);

        btnNavKeranjang.setText("Keranjang");
        btnNavKeranjang.setBorderPainted(false);
        btnNavKeranjang.setContentAreaFilled(false);
        btnNavKeranjang.addActionListener(this::btnNavKeranjangActionPerformed);
        pnlBottomNav.add(btnNavKeranjang);

        btnNavAkun.setText("Akun");
        btnNavAkun.setBorderPainted(false);
        btnNavAkun.setContentAreaFilled(false);
        btnNavAkun.addActionListener(this::btnNavAkunActionPerformed);
        pnlBottomNav.add(btnNavAkun);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottomNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBottomNav, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String keyword = txtSearch.getText().trim();
        if (keyword.isEmpty()) return;
        List<produk> hasil = produkDAO.cariProduk(keyword);
        renderGrid(hasil);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        btnSearchActionPerformed(evt); // Enter di textfield = sama seperti klik search
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnKatMugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKatMugActionPerformed
        // TODO add your handling code here:
        tampilkanProduk("Mug", 0);
    }//GEN-LAST:event_btnKatMugActionPerformed

    private void btnKatSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKatSemuaActionPerformed
        // TODO add your handling code here:
        tampilkanProduk("Semua", 0);
    }//GEN-LAST:event_btnKatSemuaActionPerformed

    private void btnKatKaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKatKaosActionPerformed
        // TODO add your handling code here:
        tampilkanProduk("Kaos", 0);
    }//GEN-LAST:event_btnKatKaosActionPerformed

    private void btnKatHoodieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKatHoodieActionPerformed
        // TODO add your handling code here:
        tampilkanProduk("Hoodie", 0);
    }//GEN-LAST:event_btnKatHoodieActionPerformed

    private void btnKatStickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKatStickerActionPerformed
        // TODO add your handling code here:
        tampilkanProduk("Sticker", 0);
    }//GEN-LAST:event_btnKatStickerActionPerformed

    private void btnKatTotebagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKatTotebagActionPerformed
        // TODO add your handling code here:
        tampilkanProduk("Totebag", 0);
    }//GEN-LAST:event_btnKatTotebagActionPerformed

    private void btnLihatSemuaKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatSemuaKategoriActionPerformed
        // TODO add your handling code here:
        tampilkanProduk("Semua", 0);
    }//GEN-LAST:event_btnLihatSemuaKategoriActionPerformed

    private void btnLihatSemuaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatSemuaProdukActionPerformed
        // TODO add your handling code here:
        tampilkanProduk("Semua", 0);
    }//GEN-LAST:event_btnLihatSemuaProdukActionPerformed

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        // TODO add your handling code here:
        keranjang k=new keranjang();
        k.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_btnCartActionPerformed

    private void btnPesanSekarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanSekarangActionPerformed
        // TODO add your handling code here:
        List<produk> data = produkDAO.getProduk("Semua", 1);
        if (!data.isEmpty()) {
            // Panggil dengan 3 parameter: (parent, modal, idProduk)
            detail_produk frame = new detail_produk(this, true, data.get(0).getIdProduk());
            frame.setLocationRelativeTo(this);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_btnPesanSekarangActionPerformed

    private void btnNavBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavBerandaActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlContent, "Beranda");
    }//GEN-LAST:event_btnNavBerandaActionPerformed

    private void btnNavPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavPesananActionPerformed
        // TODO add your handling code here:
        pesananSaya ps = new pesananSaya();
        ps.setLocationRelativeTo(this);
        ps.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnNavPesananActionPerformed

    private void btnNavKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavKeranjangActionPerformed
        // TODO add your handling code here:
        keranjang k=new keranjang();
        k.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnNavKeranjangActionPerformed
    
    private void btnNavAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavAkunActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Halaman Akun belum dibuat");
    }//GEN-LAST:event_btnNavAkunActionPerformed

    private void btnHamburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHamburgerActionPerformed

    // Query DB lalu render grid produk sesuai kategori. limit=0 artinya tanpa batas.
    private void tampilkanProduk(String kategori, int limit) {
        kategoriAktif = kategori;
        List<produk> data = produkDAO.getProduk(kategori, limit);
        renderGrid(data);
    }

    // Bersihkan grid lalu isi ulang dengan card sesuai list produk yang diberikan. 
    private void renderGrid(List<produk> data) {
        pnlProdukGrid.removeAll();
        for (produk p : data) {
            pnlProdukGrid.add(buatKartuProduk(p));
        }
        pnlProdukGrid.revalidate();
        pnlProdukGrid.repaint();
    }
    private void loadBannerImage() {
        List<produk> data = produkDAO.getProduk("Semua", 1);
        if (data.isEmpty() || data.get(0).getFotoProduk() == null || data.get(0).getFotoProduk().length == 0) {
            return; // biarkan fallback emoji "\uD83D\uDC55" yang di-set di initComponents
        }
        byte[] foto = data.get(0).getFotoProduk();
        ImageIcon asli = new ImageIcon(foto);
        int w = asli.getIconWidth();
        int h = asli.getIconHeight();
        if (w <= 0 || h <= 0) {
            return;
        }
        int boxW = 90, boxH = 90;
        double rasio = Math.min((double) boxW / w, (double) boxH / h);
        int lebarBaru = (int) (w * rasio);
        int tinggiBaru = (int) (h * rasio);
        Image scaled = asli.getImage().getScaledInstance(lebarBaru, tinggiBaru, Image.SCALE_SMOOTH);
        lblBannerImage.setIcon(new ImageIcon(scaled));
        lblBannerImage.setText(""); // hapus emoji fallback
    }
    
    private ImageIcon muatIcon(String namaFile, int ukuran) {
        java.net.URL url = getClass().getResource("icons/" + namaFile);
        if (url == null) {
            logger.warning("Icon tidak ditemukan: " + namaFile
                    + " (pastikan ada di src/merchorderstudio/icons/)");
            return null;
        }
        ImageIcon asli = new ImageIcon(url);
        Image scaled = asli.getImage().getScaledInstance(ukuran, ukuran, Image.SCALE_SMOOTH);
        return new ImageIcon(scaled);
    }
    
    private void pasangIconTombol(JButton btn, String namaFile, int ukuran) {
        ImageIcon icon = muatIcon(namaFile, ukuran);
        if (icon == null) return;
        btn.setIcon(icon);
        btn.setHorizontalTextPosition(SwingConstants.CENTER);
        btn.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn.setIconTextGap(2);
    }
    
    private void pasangIconKategoriDanNav() {
        // Bottom nav (24px, cukup kecil karena dibarengi teks)
        pasangIconTombol(btnNavBeranda, "ic_beranda.png", 22);
        pasangIconTombol(btnNavPesanan, "ic_pesanan.png", 22);
        pasangIconTombol(btnNavKeranjang, "ic_keranjang.png", 22);
        pasangIconTombol(btnNavAkun, "ic_akun.png", 22);
 
        // Kategori (28px, tombolnya 72x54 jadi icon dikasih agak besar)
        pasangIconTombol(btnKatSemua, "ic_kat_semua.png", 26);
        pasangIconTombol(btnKatKaos, "ic_kat_kaos.png", 26);
        pasangIconTombol(btnKatHoodie, "ic_kat_hoodie.png", 26);
        pasangIconTombol(btnKatMug, "ic_kat_mug.png", 26);
        pasangIconTombol(btnKatSticker, "ic_kat_sticker.png", 26);
        pasangIconTombol(btnKatTotebag, "ic_kat_totebag.png", 26);
    }
    
    
    /**
     * Bangun satu kartu produk: gambar, nama, harga, tombol keranjang.
     * Struktur ini meniru desain ProductCardTemplate.form kamu, tapi dibuat
     * lewat kode karena isinya harus berubah-ubah sesuai data DB.
     */
    private JPanel buatKartuProduk(produk p) {
        JPanel kartu = new JPanel();
        kartu.setLayout(new BorderLayout());
        kartu.setBackground(Color.WHITE);
        kartu.setBorder(BorderFactory.createLineBorder(new Color(230, 230, 230)));
 
        // -- gambar --
        JLabel lblFoto = new JLabel();
        lblFoto.setPreferredSize(new Dimension(150, 110));
        lblFoto.setHorizontalAlignment(SwingConstants.CENTER);
        if (p.getFotoProduk() != null && p.getFotoProduk().length > 0) {
            ImageIcon icon = new ImageIcon(p.getFotoProduk());
            Image scaled = icon.getImage().getScaledInstance(150, 110, Image.SCALE_SMOOTH);
            lblFoto.setIcon(new ImageIcon(scaled));
        } else {
            lblFoto.setText("No Image");
        }
        kartu.add(lblFoto, BorderLayout.NORTH);
 
        // -- info: nama + harga + tombol cart --
        JPanel info = new JPanel(new GridLayout(2, 0));
        JLabel lblNama = new JLabel(p.getNamaProduk());
        info.add(lblNama);
 
        JPanel hargaCart = new JPanel(new BorderLayout());
        JLabel lblHarga = new JLabel(p.getHargaFormatted());
        lblHarga.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lblHarga.setForeground(new Color(255, 107, 0));
        hargaCart.add(lblHarga, BorderLayout.WEST);
 
        JButton btnCartKartu = new JButton("\uD83D\uDED2"); 
        btnCartKartu.setBorderPainted(false);
        btnCartKartu.setContentAreaFilled(false);
        btnCartKartu.addActionListener(e -> {
        boolean sukses = keranjangDAO.tambahItem(sessions.idUser, p.getIdProduk(), 1, null, null, null);
            if (sukses) {
                JOptionPane.showMessageDialog(this, p.getNamaProduk() + " ditambahkan ke keranjang");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan ke keranjang, coba lagi.");
            }
        });
        hargaCart.add(btnCartKartu, BorderLayout.EAST);
 
        info.add(hargaCart);
        kartu.add(info, BorderLayout.CENTER);
 
        // -- klik gambar/kartu -> ke detail produk --
        MouseAdapter bukaDetail = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Panggil dengan Frame parent dan mode modal 'true'
                detail_produk frame = new detail_produk((java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(dashboard_home.this), true, p.getIdProduk());
                frame.setLocationRelativeTo(dashboard_home.this); // Muncul di tengah
                frame.setVisible(true);
            }
        };
        lblFoto.addMouseListener(bukaDetail);
        kartu.addMouseListener(bukaDetail);
 
        return kartu;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard_home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnHamburger;
    private javax.swing.JButton btnKatHoodie;
    private javax.swing.JButton btnKatKaos;
    private javax.swing.JButton btnKatMug;
    private javax.swing.JButton btnKatSemua;
    private javax.swing.JButton btnKatSticker;
    private javax.swing.JButton btnKatTotebag;
    private javax.swing.JButton btnLihatSemuaKategori;
    private javax.swing.JButton btnLihatSemuaProduk;
    private javax.swing.JButton btnNavAkun;
    private javax.swing.JButton btnNavBeranda;
    private javax.swing.JButton btnNavKeranjang;
    private javax.swing.JButton btnNavPesanan;
    private javax.swing.JButton btnPesanSekarang;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAppTitle;
    private javax.swing.JLabel lblBannerImage;
    private javax.swing.JLabel lblBannerLine1;
    private javax.swing.JLabel lblBannerLine2;
    private javax.swing.JLabel lblBannerLine3;
    private javax.swing.JLabel lblKategoriTitle;
    private javax.swing.JLabel lblProdukTitle;
    private javax.swing.JPanel pnlBanner;
    private javax.swing.JPanel pnlBannerText;
    private javax.swing.JPanel pnlBeranda;
    private javax.swing.JPanel pnlBerandaContent;
    private javax.swing.JPanel pnlBottomNav;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlKategoriHeader;
    private javax.swing.JPanel pnlKategoriList;
    private javax.swing.JPanel pnlKategoriSection;
    private javax.swing.JPanel pnlProdukGrid;
    private javax.swing.JPanel pnlProdukHeader;
    private javax.swing.JPanel pnlProdukSection;
    private javax.swing.JPanel pnlTopBar;
    private javax.swing.JPanel pnlTopRight;
    private javax.swing.JScrollPane scrBeranda;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
