/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package merchorderstudio;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author alewi
 */
public class itemPesanan extends javax.swing.JPanel {

    /**
     * Creates new form itemPesanann
     */
    public itemPesanan() {
        initComponents();
    }
    
    public void setNama(String nama){
        jLabel2.setText(nama);
    }
    public void setUkuran(String ukuran){
        jLabel3.setText("Ukuran : " + ukuran);
    }
    public void setCatatan(String catatan){
        jLabel4.setText("Catatan : " + catatan);
    }
    public void setQty(String qty){
        jLabel5.setText("Qty : " + qty);
    }
    public void setHarga(String harga){
        jLabel6.setText("Rp %,.0f" + harga);
    }
    public void setFoto(byte[] foto){

        if(foto == null){
            jLabel1.setIcon(null);
            return;
        }
        
        ImageIcon icon = new ImageIcon(foto);

        Image img = icon.getImage().getScaledInstance(
                80,
                80,
                Image.SCALE_SMOOTH);

        jLabel1.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel1.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel6.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setText("jLabel2");
        jPanel7.add(jLabel2);

        jLabel3.setText("jLabel3");
        jPanel7.add(jLabel3);

        jLabel4.setText("jLabel4");
        jPanel7.add(jLabel4);

        jLabel5.setText("jLabel5");
        jPanel7.add(jLabel5);

        jPanel5.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("jLabel6");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel8.add(jLabel6, java.awt.BorderLayout.NORTH);

        jPanel5.add(jPanel8, java.awt.BorderLayout.EAST);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
