/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merchorderstudio;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import config.koneksi;

/**
 *
 * @author Gunawan
 */
public class kelolaproduk_admin extends javax.swing.JFrame {
    
    private dashboard_admin dashboard;
    private String pathGambar = "";
    String mode = "ADD";
    int idProduk;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(kelolaproduk_admin.class.getName());

    /**
     * Creates new form kelolaproduk_admin
     */
    
    public kelolaproduk_admin() {
        initComponents();
        setLocationRelativeTo(null);
        mode = "ADD";
    }
    
    private void clearForm() {
        Produk.setText("");
        Harga.setText("");
        Stok.setText("");
        Gambar.setText("");
        pathGambar = "";
    }
    
    public kelolaproduk_admin(dashboard_admin dashboard) {
        initComponents();
        this.dashboard = dashboard;
        setLocationRelativeTo(null);
        mode = "ADD";
}
    
    public void setDataEdit(
        int id,
        String nama,
        String kategori,
        String harga,
        String stok,
        String ukuran,
        String deskripsi) {

    this.mode = "EDIT";
    this.idProduk = id;

    Produk.setText(nama);
    cmbKategori.setSelectedItem(kategori);
    Harga.setText(harga);
    Stok.setText(stok);
    cmbUkuran.setSelectedItem(ukuran);
    Deskripsi.setText(deskripsi);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Gambar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Produk = new javax.swing.JTextField();
        cmbKategori = new javax.swing.JComboBox<>();
        Harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Stok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbUkuran = new javax.swing.JComboBox<>();
        Deskripsi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Gambar.addActionListener(this::GambarActionPerformed);

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Pilih");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel2.setText("Produk");

        btnSimpan.setBackground(new java.awt.Color(255, 102, 0));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        jLabel3.setText("Kategori");

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kaos", "Hoodie", "Mug", "Sticker", "Totebag" }));

        jLabel4.setText("Harga");

        jLabel5.setText("Stok");

        jLabel6.setText("Gambar");

        jLabel8.setText("Ukuran");

        cmbUkuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Ukuran", "S", "M", "L", "XL", "XXL" }));

        jLabel9.setText("Deskripsi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Deskripsi)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(Gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(Produk)
                                .addComponent(jLabel2)
                                .addComponent(Harga)
                                .addComponent(jLabel4)
                                .addComponent(Stok)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addComponent(cmbUkuran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Produk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Stok, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("MerchOrder");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Studio");

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("KEMBALI");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:

        Connection conn = koneksi.getConnection();

        try {

            // VALIDASI
            if (Produk.getText().isEmpty()
                || Harga.getText().isEmpty()
                || Stok.getText().isEmpty()) {

                JOptionPane.showMessageDialog(this,
                    "Data belum lengkap!");
                return;
            }

            if (pathGambar.isEmpty()
                && mode.equals("ADD")) {

                JOptionPane.showMessageDialog(this,
                    "Pilih gambar terlebih dahulu!");
                return;
            }

            double harga;
            int stok;

            try {

                harga =
                Double.parseDouble(
                    Harga.getText());

                stok =
                Integer.parseInt(
                    Stok.getText());

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this,
                    "Harga dan stok harus berupa angka!");

                return;
            }

            // ==========================
            // MODE TAMBAH
            // ==========================
            if (mode.equals("ADD")) {

                String sql =
                "INSERT INTO produk "
                + "(nama_produk,kategori,harga,"
                + "stok,ukuran,deskripsi,foto_produk) "
                + "VALUES (?,?,?,?,?,?,?)";

                PreparedStatement pst =
                conn.prepareStatement(sql);

                pst.setString(1,Produk.getText());
                pst.setString(2,cmbKategori.getSelectedItem().toString());
                pst.setDouble(3, harga);
                pst.setInt(4, stok);
               String ukuran = cmbUkuran.getSelectedItem().toString();

                if (ukuran.equals("Pilih Ukuran")) {
                    pst.setNull(5, java.sql.Types.VARCHAR);
                } else {
                    pst.setString(5, ukuran);
                }    
                pst.setString(6, Deskripsi.getText());

                // SIMPAN FOTO KE BLOB
                File file =
                new File(pathGambar);

                FileInputStream fis =
                new FileInputStream(file);

                pst.setBinaryStream(
                    7,
                    fis,
                    (int) file.length()
                );

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,
                    "Produk berhasil disimpan!");

            }

            // ==========================
            // MODE EDIT
            // ==========================
            else {

                String sql =
                "UPDATE produk SET "
                + "nama_produk=?,"
                + "kategori=?,"
                + "harga=?,"
                + "stok=?,"
                + "ukuran=?,"
                + "deskripsi=?";

                // jika pilih gambar baru
                if (!pathGambar.isEmpty()) {

                    sql += ", foto_produk=?";
                }

                sql += " WHERE id_produk=?";

                PreparedStatement pst =
                conn.prepareStatement(sql);

                pst.setString(1,Produk.getText());
                pst.setString(2,cmbKategori.getSelectedItem().toString());
                pst.setDouble(3, harga);
                pst.setInt(4, stok);
                String ukuran = cmbUkuran.getSelectedItem().toString();

                if (ukuran.equals("Pilih Ukuran")) {
                    pst.setNull(5, java.sql.Types.VARCHAR);
                } else {
                    pst.setString(5, ukuran);
                }
                
                pst.setString(6, Deskripsi.getText());

                int index = 7;

                // update gambar jika ada gambar baru
                if (!pathGambar.isEmpty()) {

                    File file =
                    new File(pathGambar);

                    FileInputStream fis =
                    new FileInputStream(file);

                    pst.setBinaryStream(
                        index,
                        fis,
                        (int) file.length()
                    );

                    index++;
                }

                pst.setInt(index, idProduk);
                
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,
                    "Produk berhasil diupdate!");
            }

            if (dashboard != null) {
                dashboard.DataProduk();   // Refresh JTable
                dashboard.showCard("produk");
                dashboard.setVisible(true);

                this.dispose();

            } else {

                dashboard_admin admin = new dashboard_admin();
                admin.DataProduk();       // Refresh JTable
                admin.showCard("produk");
                admin.setVisible(true);

                this.dispose();
            }

                clearForm();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                "Error : " + e.getMessage());

            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();

        int result = fc.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            File imgfile = fc.getSelectedFile();

            pathGambar = imgfile.getAbsolutePath();

            Gambar.setText(pathGambar);

        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada gambar dipilih");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void GambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GambarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GambarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    
            if (dashboard != null) {
            dashboard.showCard("produk");
            dashboard.setVisible(true);
            this.dispose();
        } else {
            dashboard_admin admin = new dashboard_admin();
            admin.showCard("produk");
            admin.setVisible(true);
            this.dispose();
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new kelolaproduk_admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Deskripsi;
    private javax.swing.JTextField Gambar;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField Produk;
    private javax.swing.JTextField Stok;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JComboBox<String> cmbUkuran;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
